### ISSUE TITLE
Clarification of installation instructions

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server-harvester#1]
Can you please clarify the installation instructions?

After downloading the zip file and unzipping it to C:\temp\geoportal-server-harvester-master I try:

```
cd c:\temp\geoportal-server-harvester-master
mvn clean install
```

 This runs for 5 seconds then generates the error message:

```
[ERROR] Failed to execute goal on project geoportal-harvester-csw: Could not res
olve dependencies for project com.esri.geoportal:geoportal-harvester-csw:jar:1.0
.0-SNAPSHOT: Could not find artifact com.esri.geoportal:geoportal-commons-http:j
ar:1.0.0-SNAPSHOT -> [Help 1]
```

The full error log is here: 
[install_errors.txt](https://github.com/Esri/geoportal-server-harvester/files/271681/install_errors.txt)

Am I doing something wrong, or is there a different problem? (This is my first time using MVN).

I'm using Apache Tomcat 8.0.35 and jdk1.8.0_92 on Windows 7. Thanks

**Comment by pandzel** [comment]
Stephen,

Harvester is still under development and not released yet. If you pull recent changes you will be able to compile without the error. The error was caused by invalid reference in one of the projects pom.xml file (thanks for attempting building it).

There are several ways envisioned how the harvesting could be conducted. Currently, you can either deploy war file on Apache Tomcat and use REST end points (no real UI available yet), or use somewhat complicated command line.

You would be able to pull data from either WAF or CSW repository and push to the catalog.

Let me know which option is feasible for you, then I will guide you how to do it.

**Comment by slead** [comment]
Cool, thanks for the info. In terms of keeping my harvester installation up-to-date with your GitHub version, what is the recommended approach? Would I clone the repo then synchronise GitHub each time there's a change - if so do I need to rebuild the code using mvn each time?

I'm actually evaluating this for a client, so I'll probably recommend that they stick with Geoportal SErver 1.2.6 for the meanwhile, since this is all so new. Do you have a timeline for when 2.x will be released?

Thanks again,
Steve

**Comment by pandzel** [comment]
Once you cloned repository into your local folder, it's enough to invoke 'git pull' command inside the folder using GIT bash. Or, you could use any available GUI tool to do the same. The short answer is: yes, you need to do pull keep your source up to date. Then, you need to rebuild the code.

This is good as long as you are not planning to make any changes to the source. However, if you do then there are several ways to proceed, although the recommended one would be to create a fork (see: 'Fork' button). I don't do fork myself, since I have a full access to the repository (read/write); all I do is to create so called development branches, then merge it back to the main branch.

When it comes to Geoportal versions, 1.2.x is more all-in-one solution, while 2.x.x aims more toward distributed environments.
