### ISSUE TITLE
Harvesting from data.gov.uk

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server-harvester#127]
Hi,
Can the data from the data.gov repository of other countries other than the US (for example data.gov.uk, data.gov.in) be harvested through the Harvester using the input broker as "DATA.GOV"?

**Comment by mhogeweg** [comment]
hi, the data.gov input broker was specifically created for the United States national open data site https://www.data.gov and the associated 'Project Open Data' site implementations. It has created a specific DCAT profile that includes elements for federal agencies and bureaus to identify themselves via formal organization codes. 

However, you can harvest data.gov.uk using the harvester already. From the list of source brokers, select CKAN instead of data.gov.

![image](https://user-images.githubusercontent.com/394890/92652947-7fbdf280-f2a2-11ea-979f-e266635ddaa9.png)

In the configuration dialog, leave the API Key empty. Some CKAN implementations require getting this key before they allow harvesting.
