### ISSUE TITLE
Unable to Harvest secured Map services from ArcGIS server

### ISSUE THREAD

**Issue by shamnas8vdk** [Esri/geoportal-server-harvester#128]
Am unable to hervest secured Map services which is federated with ArcGIS portal, It is only harvesting the services which are not secured. Is there a way to harvest secured services from ArcGIS Server ?

**Comment by mhogeweg** [comment]
We had decided to not harvest these protected services. This mainly because if users discover a protected service, they would not necessarily be able to use it (it is protected). Users within an ArcGIS organization would use ArcGIS Portal to discover these services, either from the Portal web application or from clients such as ArcGIS Pro or ArcGIS Earth. Geoportal is not intended to replace that role of ArcGIS Portal.
