### ISSUE TITLE
Support harvesting to ArcGIS Online/Portal

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server-harvester#3]
As an administrator I want to be able to setup a regular process of harvesting content from one or more sources into my ArcGIS Online subscription/Portal for ArcGIS instance.

**Comment by pandzel** [comment]
Added.

**Comment by xlhomme** [comment]
Hi 
Can you explain how to configure the harvester to a Portal for ArcGIS instance ?
thanks 
best regards 
xll

**Comment by pandzel** [comment]
The easiest way would be to declare output broker through harvester UI. Click "Broker" button on the left pane, then "Add" button under "Output brokers" section.

Popup dialog box will let you define appropriate broker. "ArcGIS Portal" should be selected as a type, then  name, url, folder id (optional), user name and password fields should be populated with relevant information.

name - is an arbitrary name assigned to the broker,
url - is an url to the root of the Portal. By "root" I mean such url where the "/sharing" part will be appended. If this is ArcGIS Online, the only valid value is https://www.arcgis.com/. If this is your local instance it will be something like: https://<your server and domain>:7443/arcgis/
folder id - is an actual id of the folder items will be harvested into; you may leave it blank
user name, password - credentials of the user account on the Portal.

Once it's done, a task must be created with output redirected to that broker.

Notes!

1. If this is your local instance of the Portal, you would avoid to select "localhost" as a server name and use fully qualified name,
2. All the communication has to go through https protocol, so if this is you just freshly installed Portal, it will be missing SSL certificate (to be more precise: it has only self-signed certificate). Harvester will fail to communicate with such instance. In order to succeed you either purchase a valid certificate from the certificate provider and install it on the Portal, or declare that self-signed certificate as valid so Java knows it safe to access a site with such certificate (you do it using keytool application on 'cacerts' file - let me know if you need more guidance about that).
3. No matter what you harvest from, Portal will only accept what make sense to it. Harvester may harvest some metadata with some urls in it and it will create a Portal item from it. So, if there is an url to the MapServer, ImageServer, WMS, etc. harvester will gladly deal with it, but if metadata has no url or has url to something which Portal does not recognize, no item will be created.
4. Primary tool to troubleshoot the issues is a log file.

Let me know if this information is enough or you need more help.

P.
