### ISSUE TITLE
How to harvest a Entreprise Geodatabase

### ISSUE THREAD

**Issue by xlhomme** [Esri/geoportal-server-harvester#45]
Hi
 In order to harvest an Entreprise Geodatabase, should I export all the metada into XML metadata files ?
 Is It possible to create a connector ? 

Best regards

**Comment by pandzel** [comment]
In general, exporting XML or JSON from any source, storing it in a folder, then harvesting this folder is always a viable option. However, in your case it would be probably a very tedious job.

A better option would be to write a custom inbound adapter. In order to do that you would need to have an access to the ArcGIS Runtime SDK.

**Comment by xlhomme** [comment]
Hi 
If you have access to an arcsde sdk (files :  jpe_sdk.jar, jsde_sdk.jar) it should be possible to write an harvester. GeoNetwork has such an harvester.

https://geonetwork-opensource.org/manuals/2.10.4/eng/users/managing_metadata/harvesting/sde/index.html

**Comment by mhogeweg** [comment]
that is correct. but similar to geonetwork, this would require additional installation, since we cannot ship those jar files with the harvester. similarly, the geonetwork license is not compatible with our geoportal license so it prevents us from combining their harvester into ours. open source/proprietary doesn't make a difference here. it's the license that dictates what you can do with some component.

In ArcMap we have a publishing client that pushes metadata to a geoportal (instead of a harvester pulling). Do you use ArcMap? if so, check out https://github.com/Esri/geoportal-server/tree/master/components/desktop/PublishClient

**Comment by andrewrudin-austin** [comment]
Is the 10.6 ArcCatalog Publishing Client compatible with Harvester version 2.5.2?  I have a brand new GeoPortal Server/Harvester on the same server. I'm trying to populate it with XML's extracted from a geodatabase.  When I follow the Publishing Client use instructions I get errors.  I tried pointing it at both the /geoportal and the /harvester server URLs with no luck.

**Comment by zguo** [comment]
The ArcCatalog Publish Client is intended for publishing to geoportal 1.2.x, if your metadata from geodtabase is already extracted to a folder, you can use harvester to harvest the folder into a geoportal 2.x instance.

**Comment by zguo** [comment]
Implemented in the updated harvester, now you can harvest geodatabase metadata directly through JDBC database broker, please see https://github.com/Esri/geoportal-server-harvester/wiki/Brokers#jdbc-database.

**Comment by mhogeweg** [comment]
you should not have to rebuild the harvester for this. Just putting the JDBC driver in the Tomcat/lib folder, restarting Tomcat after this, and providing the correct info should be sufficient. Can you provide the error message?

in the fields for the select statement, primary key, title and description: does this match your table structure? is the database_name unique?

**Comment by Zahid-Mia** [comment]
Hi Marten

Thank you very much for your reply.
As you suggested please see the error message below I am having. Please note I am trying this from my local computer. Log file is also attached herewith.

Error opening JDBC connection to: jdbc:sqlserver://desktop-ni994f7:1433;databaseName=EWR

Please see below for the screen shot for the broker definition, dbo.gdb_items table structure etc.
I appreciate your patient supporting the Geoportal users.

Thanks
Zahid

[cid:65d6841a-948e-4a9c-99bb-84965c223abf]
[cid:68fc0b27-1f9e-470e-8e17-42563987fa4e]
________________________________

**Comment by mhogeweg** [comment]
hmm... seems the log file did not get attached,

question:
- can you sign in to the SQL Server (jdbc:sqlserver://desktop-ni994f7:1433;databaseName=EWR) from SQL Server Management Studio?
- if so, since you sign in using account 'gisadmin' what is the default database for this user? do they have access to EWR?
- if so, what is the structure of the table dbo.gdb_items? 
- is this an Esri Enterprise Geodatabase? if so:
  - use OBJECTID as primary key 
  - use 'Name' as the title column
  - use 'Documentation' as the field with the metadata for feature classes

**Comment by Zahid-Mia** [comment]
Hi Marten
Thank you again for your reply.
Please see the attachment for the responses to your queries along with screen shot for each step.
Earlier I attached the log file as zip file with other files in the logs folder. Anyway, please see the attachment for the logfile as a single file here with. I have followed your steps and still couldn't resolve.
I hope the above helps.

Thanks
Zahid

________________________________
